baseURL = 'https://grind.rip'
languageCode = 'en-us'
title = 'grind.rip'
theme = 'grind-rip'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    highlight = true
    style = "doom-one"

[params]

[params.about]
title = 'grind.rip'
description = 'From Grind Hell, with Love'

[[params.socials]]
icon = 'fa-brands fa-github'
name = 'GitHub'
url = 'https://github.com/grind-rip'

[[menus.main]]
name = 'algorithms'
pageRef = '/algorithms'
weight = 10

[[menus.main]]
name = 'docs'
pageRef = '/docs'
weight = 20

[[menus.main]]
name = 'leetcode'
pageRef = '/leetcode'
weight = 30

[[menus.main]]
name = 'journal.md'
pageRef = '/journal.md'
weight = 40
