baseURL = 'https://grind.rip'
languageCode = 'en-us'
title = 'grind.rip'
theme = 'grind-rip'

[module]
[[module.mounts]]
  excludeFiles = [
    'algorithms/algorithms',
    'docs/docs',
    'leetcode/leetcode'
  ]
  source = 'content'
  target = 'content'

[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  highlight = true
  style = "doom-one"
  [markup.goldmark]
    [markup.goldmark.extensions]
    taskList = false
    typographer = false

[params]
  [params.about]
  title = 'grind.rip'
  description = 'From Grind Hell, with Love'

  [[params.socials]]
  icon = 'fa-brands fa-github'
  name = 'GitHub'
  url = 'https://github.com/grind-rip'

[[menus.main]]
name = 'algorithms'
pageRef = '/algorithms'
weight = 10

[[menus.main]]
name = 'docs'
pageRef = '/docs'
weight = 20

[[menus.main]]
name = 'leetcode'
pageRef = '/leetcode'
weight = 30

[[menus.aside]]
name = 'blind_75.md'
pageRef = '/blind_75.md'
weight = 10

[[menus.aside]]
name = 'grind_169.md'
pageRef = '/grind_169.md'
weight = 20

[[menus.aside]]
name = 'interviews.md'
pageRef = '/interviews.md'
weight = 30

[[menus.aside]]
name = 'journal.md'
pageRef = '/journal.md'
weight = 40

[[menus.aside]]
name = 'notes.md'
pageRef = '/notes.md'
weight = 50

[[menus.aside]]
name = 'roadmap.md'
pageRef = '/roadmap.md'
weight = 60
