baseURL = 'https://grind.rip'
languageCode = 'en-us'
title = 'grind.rip'
theme = 'grind-rip'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    highlight = true
    style = "doom-one"

[params]

[params.about]
title = 'grind.rip'
description = 'From Grind Hell, with Love'

[[params.socials]]
icon = 'fa-brands fa-github'
name = 'GitHub'
url = 'https://github.com/grind-rip'
