baseURL = 'https://grind.rip'
languageCode = 'en-us'
title = 'grind.rip'
theme = 'grind-rip'

# Google Analytics measurement ID (Google Analytics 4)
[services]
  [services.googleAnalytics]
    id = 'G-L6YLMG3HFY'

[module]
  [[module.mounts]]
  excludeFiles = [
    'algorithms/_algorithms',
    'data-structures/_data-structures',
    'docs/_docs',
    'interviews/_interviews',
    'leetcode/_leetcode',
    'system-design/_system-design',
  ]
  source = 'content'
  target = 'content'

[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  highlight = true
  # See: https://xyproto.github.io/splash/docs/
  style = 'doom-one'
  [markup.goldmark]
    [markup.goldmark.extensions]
    taskList = false
    typographer = false
    [markup.goldmark.renderer]
    unsafe = true

[params]
  [params.about]
  title = 'grind.rip'
  description = 'From Grind Hell, with Love'

  [params.seo]
  meta_og_title = 'grind.rip'
  meta_og_description = 'From Grind Hell, with Love'
  meta_og_site_name = 'grind.rip'
  meta_og_image = 'grind-rip-256x256.png'
  meta_twitter_title = 'grind.rip'
  meta_twitter_description = 'From Grind Hell, with Love'
  meta_twitter_site = '@grind_rip'
  meta_twitter_creator = '@grind_rip'
  meta_twitter_image = 'grind-rip-256x256.png'

  [[params.socials]]
  icon = 'fa-brands fa-github'
  name = 'GitHub'
  url = 'https://github.com/grind-rip'

  [[params.socials]]
  icon = 'fa-brands fa-x-twitter'
  name = 'X'
  url = 'https://twitter.com/grind_rip'

  [[params.socials]]
  icon = 'fa-brands fa-youtube'
  name = 'YoutTube'
  url = 'https://www.youtube.com/@grind-rip'

  [[params.socials]]
  icon = 'fa-brands fa-discord'
  name = 'Discord'
  url = 'https://discord.gg/KgdQCYpZ'

  [[params.socials]]
  icon = 'fa-solid fa-envelope'
  name = 'Email'
  url = 'mailto:0x@nickolaskraus.io'

[[menus.main]]
name = 'algorithms'
pageRef = '/algorithms'
weight = 10

[[menus.main]]
name = 'data_structures'
pageRef = '/data-structures'
weight = 20

[[menus.main]]
name = 'system_design'
pageRef = '/system-design'
weight = 30

[[menus.main]]
name = 'leetcode'
pageRef = '/leetcode'
weight = 40

[[menus.main]]
name = 'docs'
pageRef = '/docs'
weight = 50

[[menus.main]]
name = 'interviews'
pageRef = '/interviews'
weight = 60

[[menus.aside]]
name = 'blind_75.md'
pageRef = '/blind_75.md'
weight = 10

[[menus.aside]]
name = 'grind_169.md'
pageRef = '/grind_169.md'
weight = 20

[[menus.aside]]
name = 'leetcode_75.md'
pageRef = '/leetcode_75.md'
weight = 30

[[menus.aside]]
name = 'neetcode_150.md'
pageRef = '/neetcode_150.md'
weight = 40

[[menus.aside]]
name = 'journal.md'
pageRef = '/journal.md'
weight = 50

[[menus.aside]]
name = 'roadmap.md'
pageRef = '/roadmap.md'
weight = 60
