name = 'grind.rip'
license = 'MIT'
licenselink = 'https://github.com/grind-rip/grind-rip-site/blob/master/LICENSE'
description = 'A Hugo theme for grind.rip'

homepage = 'https://github.com/grind-rip/grind-rip-site'
demosite = 'https://grind.rip'

[author]
  name = 'Nickolas Kraus'
  homepage = 'https://nickolaskraus.io'
